name: Fedora 31 - kernel-surface

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:31

    steps:
    - name: Fetch repository
      uses: actions/checkout@v2
    - name: Decrypt certificates
      env:
        LS_PASSWORD: ${{ secrets.LS_PASSWORD }}
      run: |
        pkg/secrets/decrypt.sh -p "$LS_PASSWORD" -f pkg/secrets/gpg/surface_gpg.key.gpg
        pkg/secrets/decrypt.sh -p "$LS_PASSWORD" -f pkg/secrets/sb/surface_sb.key.gpg
    - name: Install certificates
      run: |
        gpg --no-tty --batch --yes --import pkg/secrets/gpg/surface_gpg.key
        cp pkg/secrets/sb/surface_sb.key pkg/fedora/kernel-surface/surface.key
        cp pkg/secrets/sb/surface_sb.crt pkg/fedora/kernel-surface/surface.crt
    - name: Install build-dependencies
      run: |
        dnf install -y rpmdevtools findutils openssl openssl-devel kmod patch
        dnf install -y bash tar git-core sbsigntools bzip2 xz findutils gzip
        dnf install -y m4 perl-interpreter perl-Carp perl-devel perl-generators
        dnf install -y make diffutils gawk gcc binutils redhat-rpm-config
        dnf install -y hmaccalc bison flex net-tools hostname bc elfutils-devel
        dnf install -y python3-devel
    - name: Build kernel
      run: |
        cd pkg/fedora/kernel-surface
        ../makerpm -sk linux-surface
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: kernel-surface-fc31
        path: pkg/fedora/kernel-surface/out/x86_64
